# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dpJc+nnurz9jzUpOJ19nCkZhNHMHOzx3Ip0q2pN7A04H6x9kcmKFki/1wyaqD89fDhSsxiG4mins55IFTowGVWhoR43UxQrONh2nkzSS7YmwxTi8bJ7mSPhpASUwVXMOocPRT9ev7bqcpdAkQ1VJMkPMPmGQeXTzjWQj6UG65Tt8yr1Gym+KBB4bb+cP0kRXdnFoiLPEni6NtD8+Cs3P1Qj/WhQDLE9e59GK7TyJ3unwkpwOoWllX/lyiJLhY1c+5PhC2DE7J000SvFK40olSYckTq93eKnTn1IRGvNnhn1059Yq035mDxiRerAGsmYMOv85FbQSRNGpKC8oso3WggY/DWVh+gUKVH8aBP7llJdgIVRd0X8YR+7yOemly1ptooZwTaWip95L1dsPqAu639vmVtnCJ8wY/SESnNZadKm8RSHSnDX6iaHiGLeaO/PaoBbYZDA7YP4Meoo+4Z4w6Sp0/ZYlfI7shsVTdd8PQtEv5ZbjViOxGO9edealf8C39TeRO9RMn8capn6ky5hOAmKFnC+yhkxsDUkO6PnACVFQTxGtuoQCapj5qbnqTnJVXaRTl6ZCKPccUAR3ymezF147WSKrdqnI78YTjwCWcI+dMEZcN4cQvMkCvLLk0xbNTUrgtjf8LvPFSMSYfnxqIQyGSbC2zW0FLQ/U+2VykFM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
