travis:
  secure:
    BINSTAR_TOKEN: dpJc+nnurz9jzUpOJ19nCkZhNHMHOzx3Ip0q2pN7A04H6x9kcmKFki/1wyaqD89fDhSsxiG4mins55IFTowGVWhoR43UxQrONh2nkzSS7YmwxTi8bJ7mSPhpASUwVXMOocPRT9ev7bqcpdAkQ1VJMkPMPmGQeXTzjWQj6UG65Tt8yr1Gym+KBB4bb+cP0kRXdnFoiLPEni6NtD8+Cs3P1Qj/WhQDLE9e59GK7TyJ3unwkpwOoWllX/lyiJLhY1c+5PhC2DE7J000SvFK40olSYckTq93eKnTn1IRGvNnhn1059Yq035mDxiRerAGsmYMOv85FbQSRNGpKC8oso3WggY/DWVh+gUKVH8aBP7llJdgIVRd0X8YR+7yOemly1ptooZwTaWip95L1dsPqAu639vmVtnCJ8wY/SESnNZadKm8RSHSnDX6iaHiGLeaO/PaoBbYZDA7YP4Meoo+4Z4w6Sp0/ZYlfI7shsVTdd8PQtEv5ZbjViOxGO9edealf8C39TeRO9RMn8capn6ky5hOAmKFnC+yhkxsDUkO6PnACVFQTxGtuoQCapj5qbnqTnJVXaRTl6ZCKPccUAR3ymezF147WSKrdqnI78YTjwCWcI+dMEZcN4cQvMkCvLLk0xbNTUrgtjf8LvPFSMSYfnxqIQyGSbC2zW0FLQ/U+2VykFM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
